FROM luckycatalex/radare2-base:5.6.8

# Label base
LABEL maintainer="Alex Kislitsa"

# Initilise base user
USER r2
WORKDIR /home/r2
ENV HOME /home/r2

# Setup r2pm
RUN \
  export PATH=~/.local/bin:~/.r2env/bin:$PATH && r2pm init && r2pm update && r2pm -ci r2ghidra
